name: 'Get & cache dependencies'
description: 'Cache dependencies to speed up workflow runs'
inputs:
  caching:
    description: 'The caching strategy to use'
    required: false
    default: 'true'
outputs:
  cache-hit:
    description: 'Whether the cache was hit'
    value: ${{ steps.install.outputs.cache }}    
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: |
        npm ci
        echo "cache='${{ inputs.caching }}'" >> $GITHUB_OUTPUT
      shell: bash